apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-server
spec:
  replicas: 2
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: myserver
    spec:     # pod spec                  
      containers: 
      - name: myserver 
        image: my-server # image we pushed
        ports:
        - containerPort: 3000
